application: bigmultiplayerchess
runtime: python39
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT main:app --timeout 180000 --workers 1 --threads 1

default_expiration: "300d 5h"

handlers:
- url: /manifest.webapp
  static_files: manifest/manifest.json
  upload: manifest/manifest.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json

- url: /manifest-noads.webapp
  static_files: manifest/manifest-noads.json
  upload: manifest/manifest-noads.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /transient/*
  static_dir: transient
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: /robots.txt
  static_files: transient/robots.txt
  upload: transient/robots.txt

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml

- url: /channel.html
  static_files: static/channel.html
  upload: static/channel.html

- url: /gameon/static/*
  static_dir: gameon/static
  http_headers:
    Vary: Accept-Encoding


- url: /favic(.+)
  static_files: static/icons/favic\1
  upload: static/icons/favic(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /apple(.+)
  static_files: static/icons/apple\1
  upload: static/icons/apple(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /mstile(.+)
  static_files: static/icons/mstile\1
  upload: static/icons/mstile(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /android(.+)
  static_files: static/icons/android\1
  upload: static/icons/android(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /browserconfig.xml
  static_files: static/icons/browserconfig.xml
  upload: static/icons/browserconfig.xml
  http_headers:
    Vary: Accept-Encoding

- url: .*
  script: main.app

instance_class: F1
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

inbound_services:
- warmup

builtins:
- appstats: on
